server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: "host=192.168.178.179 user=showyquasar88 password=showyquasar88 dbname=tiktok port=5432 sslmode=disable TimeZone=Asia/Shanghai"
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

trace:
  endpoint: otel-collector:4318
  sampler: 1.0
  environment: development

log:
  level: debug
  filename: logs/app.log
  maxSize: 100
  maxAge: 7
  maxBackups: 30
