server:
  http:
    addr: 0.0.0.0:8000
    timeout: 30s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 30s
data:
  database:
    driver: postgres
    source: "host=192.168.178.179 user=showyquasar88 password=showyquasar88 dbname=tiktok port=5432 sslmode=disable TimeZone=Asia/Shanghai"
  redis:
    addr: 192.168.178.179:6379
    password: showyquasar88
    read_timeout: 0.2s
    write_timeout: 0.2s

trace:
  endpoint: http://localhost:14268/api/traces
  sampler: 1.0
  environment: dev

log:
  level: debug
  filename: logs/app.log
  maxSize: 100
  maxAge: 7
  maxBackups: 30

security:
  aesKey: 5c259313928ef6edc1a2a56f7753121b1906ae39eb8b002d1b6b56d1a3782359
  aesIv: 104f2c7af8354aeb75f8a35fb52ac650
  bcrypt_cost: 12
  jwt:
    secret: cKtHqyLVQiZi8RRDyEoE6FxV34Wj9nCWsifnrnZt9rA=  # jwt 密钥
    expire: 86400           # token 过期时间
    refreshExpire: 86400  # 刷新token过期时间
